-- =============================================================================
-- 03_create_foreign_keys.sql
-- Projeto: Migração SCCI/Originação - Firebird 3 -> PostgreSQL 18 (C6 Bank)
--
-- ESCOPO:
--   232 FOREIGN KEYs criadas em uma única etapa (criação + validação imediata).
--   PRIMARY KEYs já existem (criadas pelo Converter / 00_create_python_tables).
--
-- ESTRATÉGIA - SINGLE-STEP:
--   Cada ALTER TABLE ADD CONSTRAINT ... FOREIGN KEY cria a constraint e valida
--   os dados existentes em uma única operação.
--
--   Por que NÃO usamos NOT VALID + VALIDATE em duas etapas?
--   - A separação NOT VALID + VALIDATE existe no PostgreSQL para dois cenários:
--     (a) lock mais fraco durante validação (SHARE UPDATE EXCLUSIVE em vez de
--         SHARE ROW EXCLUSIVE), permitindo DML concorrente
--     (b) adiar o scan pesado para janela posterior não-crítica
--   - No nosso cenário a aplicação está OFFLINE (sem DML concorrente) e a
--     validação acontece dentro da janela mesmo. Nenhum dos dois benefícios
--     se aplica. A complexidade extra não paga nada.
--
-- ISOLAÇÃO DE FALHAS:
--   Sem BEGIN/COMMIT envolvendo o conjunto - cada ALTER TABLE roda em autocommit.
--   Se uma FK falhar (órfão de integridade no Firebird), as outras 231 seguem
--   sendo criadas. O erro fica isolado a uma única constraint para investigação.
--
-- PRÉ-REQUISITOS:
--   1. Cargas concluídas (Converter Inst. 1, Inst. 2, Python loader)
--   2. Script 02_create_indexes.sql executado (acelera o scan de validação)
--   3. Tabelas referenciadas com PK (Converter cria; Python via script 00)
--
-- IDEMPOTÊNCIA:
--   NÃO idempotente (PostgreSQL não tem ADD CONSTRAINT IF NOT EXISTS para FKs).
--   Recovery em caso de re-execução: usar a query de verificação no final para
--   identificar quais FKs faltam, e re-executar apenas essas linhas.
--
-- TUNING RECOMENDADO:
--   SET maintenance_work_mem = '2GB';
--   SET statement_timeout = 0;
-- =============================================================================

\timing on
SET client_min_messages = WARNING;
SET maintenance_work_mem = '2GB';
SET statement_timeout = 0;

-- -----------------------------------------------------------------------------
-- 232 FOREIGN KEYs (criação + validação imediata, autocommit por statement)
-- -----------------------------------------------------------------------------

ALTER TABLE CONFIGURACAO_SISAT_USUARIO ADD CONSTRAINT R_CONFIGURACAO_SISAT_USUARIO FOREIGN KEY (USUARIO) REFERENCES USUARIO;
ALTER TABLE CONFIGURACAO_SISAT_USUARIO ADD CONSTRAINT R_USUARIO_CONF_SUBSTITUTO FOREIGN KEY (CO_USUARIO_SUBSTITUTO) REFERENCES USUARIO;
ALTER TABLE CONFIGURACAO_SISAT_USUARIO ADD CONSTRAINT R_PERFIL_ATENDIMENTO_USUARIO FOREIGN KEY (NU_PERFIL_ATENDIMENTO) REFERENCES PERFIL_ATENDIMENTO_SISAT;
ALTER TABLE ENTIDADES ADD CONSTRAINT R_75 FOREIGN KEY (CO_CAMARA_ARBITRAL) REFERENCES ENTIDADES;
ALTER TABLE ENTIDADES ADD CONSTRAINT R_74 FOREIGN KEY (CO_ENTIDADE_ARBITRAGEM) REFERENCES ENTIDADES;
ALTER TABLE ENTIDADES ADD CONSTRAINT R_FK_ENTIDADES FOREIGN KEY (GESTOR) REFERENCES ENTIDADES;
ALTER TABLE PERFIL ADD CONSTRAINT R_FK_ENTIDADES2 FOREIGN KEY (COD_ENT) REFERENCES ENTIDADES;
ALTER TABLE PERFIL_FUNCAO ADD CONSTRAINT R_FK_PERFIL_FUNCAO FOREIGN KEY (CODIGO) REFERENCES FUNCAO;
ALTER TABLE PERFIL_FUNCAO ADD CONSTRAINT R_FK_PERFIL_F_PERFIL FOREIGN KEY (COD_PERFIL) REFERENCES PERFIL;
ALTER TABLE USUARIO ADD CONSTRAINT R_FK_USU_PERFIL FOREIGN KEY (PERF_SECUNDARIO) REFERENCES PERFIL;
ALTER TABLE USUARIO ADD CONSTRAINT R_FK_USU_PERFIL2 FOREIGN KEY (PERF_PRIMARIO) REFERENCES PERFIL;
ALTER TABLE USUARIO ADD CONSTRAINT R_FK_USU_ENTIDADES FOREIGN KEY (ENT_SECUNDARIA) REFERENCES ENTIDADES;
ALTER TABLE USUARIO ADD CONSTRAINT R_FK_USU_ENTIDADES2 FOREIGN KEY (ENT_PRIMARIA) REFERENCES ENTIDADES;
ALTER TABLE USUARIO_FUNCAO ADD CONSTRAINT XFK1USUARIO_FUNCAO FOREIGN KEY (CODIGO) REFERENCES FUNCAO ON DELETE CASCADE;
ALTER TABLE USUARIO_FUNCAO ADD CONSTRAINT XFK2USUARIO_FUNCAO FOREIGN KEY (USUARIO) REFERENCES USUARIO ON DELETE CASCADE;
ALTER TABLE ITEMDEMENU ADD CONSTRAINT R_FK_ITEMDEMENU_ACAO FOREIGN KEY (NOMEACAO) REFERENCES ACAO;
ALTER TABLE SISTARQ ADD CONSTRAINT R_FK_SISTARQ FOREIGN KEY (IDPAI) REFERENCES SISTARQ;
ALTER TABLE SISTARQ ADD CONSTRAINT R_FK_SISTARQ_TIPO FOREIGN KEY (CO_DOC_DOSSIE) REFERENCES TIPO_DOC_DOSSIE;
ALTER TABLE SISTARQ ADD CONSTRAINT R_FK_SISTARQ2 FOREIGN KEY (CO_HIERARQUIA_DOCUMENTO) REFERENCES SISTARQ;
ALTER TABLE PERFIL_SISTARQ ADD CONSTRAINT XFK1_PERFIL_SISTARQ FOREIGN KEY (COD_PERFIL) REFERENCES PERFIL ON DELETE CASCADE;
ALTER TABLE PERFIL_SISTARQ ADD CONSTRAINT XFK2_PERFIL_SISTARQ FOREIGN KEY (ID) REFERENCES SISTARQ ON DELETE CASCADE;
ALTER TABLE CONTROLEVERSAO ADD CONSTRAINT R_CONTROLEVERSAO_SISTARQ FOREIGN KEY (ID) REFERENCES SISTARQ ON DELETE CASCADE;
ALTER TABLE MOVS_GARANTIA ADD CONSTRAINT R_102 FOREIGN KEY (COD_ENT) REFERENCES ENTIDADES;
ALTER TABLE POSICAO_MENSAL_GESTOR ADD CONSTRAINT R_104 FOREIGN KEY (COD_ENT) REFERENCES ENTIDADES;
ALTER TABLE PESSOA_PRETENDENTE ADD CONSTRAINT R_PESSOA_PRINCIPAL FOREIGN KEY (NU_PESSOA_PRINCIPAL, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE PRG_GOVERNO_PRETENDENTE ADD CONSTRAINT R_127 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE COND_AQUIS_PRETENDENTE ADD CONSTRAINT R_126 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE COND_MORADIA_PRETENDENTE ADD CONSTRAINT R_125 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE CREDITO_PRETENDENTE ADD CONSTRAINT R_135 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE DEPENDENTE_PRETENDENTE ADD CONSTRAINT R_145 FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE;
ALTER TABLE DESPESA_PRETENDENTE ADD CONSTRAINT R_132 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE ON DELETE CASCADE;
ALTER TABLE DIVIDA_PRETENDENTE ADD CONSTRAINT R_133 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE FINANC_PRETENDENTE ADD CONSTRAINT R_124 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE FONTE_RENDA_PRETENDENTE ADD CONSTRAINT R_R_FONTE_RENDA__PESSOA_PRET FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE IMOVEL_PRETENDENTE ADD CONSTRAINT R_136 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE IMOVEL_PRETENDIDO ADD CONSTRAINT R_141 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE PESSOA_PRETENDENTE ADD CONSTRAINT R_129 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE REF_PRETENDENTE ADD CONSTRAINT R_134 FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE IMOVEL_PRETENDENTE ADD CONSTRAINT R_PESSOA_PRET__IMOVEL_PRET FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE BEN_PRETENDENTE ADD CONSTRAINT R_BEN_PRET__PESSOA_PRET FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE BEN_PRETENDENTE ADD CONSTRAINT R_BEN_PRET__PRETENDENTE FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE ON DELETE CASCADE;
ALTER TABLE DIVIDA_PRETENDENTE ADD CONSTRAINT R_PESSOA_PRET__DIVIDA_PRET FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE REF_PRETENDENTE ADD CONSTRAINT R_PESSOA_PRET__REF_PRET FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE DESPESA_PRETENDENTE ADD CONSTRAINT R_PESSOA_PRET__DESPESA_PRET FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE ANDAMENTO_RELATORIO ADD CONSTRAINT R_ANDAMENTO_RELATORIO FOREIGN KEY (USUARIO) REFERENCES USUARIO ON DELETE CASCADE;
ALTER TABLE REQUISITOS_ACAO ADD CONSTRAINT R_REQUISITOS_ACAO FOREIGN KEY (NOME) REFERENCES ACAO;
ALTER TABLE CRI ADD CONSTRAINT R_USUARIO_RESPONSAVEL__CRI FOREIGN KEY (CO_USUARIO_RESPONSAVEL_CRI) REFERENCES USUARIO ON DELETE SET NULL;
ALTER TABLE CTRSDOCRI ADD CONSTRAINT R_151 FOREIGN KEY (COD_CRI) REFERENCES CRI;
ALTER TABLE PARCELAS_LASTRO_CRI ADD CONSTRAINT R_153 FOREIGN KEY (COD_CRI) REFERENCES CRI;
ALTER TABLE AMORTCRI ADD CONSTRAINT R_152 FOREIGN KEY (COD_CRI) REFERENCES CRI;
ALTER TABLE ATENDIMENTO_FGTS ADD CONSTRAINT R_155 FOREIGN KEY (CO_USUARIO_ATENDIMENTO) REFERENCES USUARIO;
ALTER TABLE PESSOA_FGTS ADD CONSTRAINT R_122 FOREIGN KEY (NU_ATENDIMENTO) REFERENCES ATENDIMENTO_FGTS;
ALTER TABLE AGEND_PRETENDENTE ADD CONSTRAINT R_AGEND_PRETEND FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE;
ALTER TABLE CUSTA_MUTUARIO ADD CONSTRAINT R_CUSTA_MUTUARIO_TIPO_CUSTA FOREIGN KEY (CO_TIPO_CUSTA) REFERENCES TIPO_CUSTA;
ALTER TABLE CUSTA_MUTUARIO ADD CONSTRAINT R_CUSTA_MUTUARIO_USUARIO FOREIGN KEY (NO_USUARIO_CADASTRO) REFERENCES USUARIO;
ALTER TABLE TRAMITACAO_JURIDICO ADD CONSTRAINT R_TRAMITACAO_JURIDICO_USUARIO FOREIGN KEY (NO_USUARIO) REFERENCES USUARIO;
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT R_ENTIDADE_OCORRENCIA_SISAT FOREIGN KEY (CO_ENTIDADE_EXECUCAO) REFERENCES ENTIDADES;
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT R_244 FOREIGN KEY (NU_OCORRENCIA_ANTERIOR) REFERENCES OCORRENCIA_SISAT;
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT R_DOC_GERADO_OCORRENCIA_SISAT FOREIGN KEY (NU_ID_DOCUMENTO_GERADO) REFERENCES SISTARQ ON DELETE SET NULL;
ALTER TABLE STATUS_FINALIZA_TAREFA_DOC ADD CONSTRAINT R_STATUS_FIN_TAREFA_DOC__01 FOREIGN KEY (CO_TAREFA_PADRAO, CO_STATUS_FINALIZACAO) REFERENCES STATUS_FINALIZA_TAREFA;
ALTER TABLE TAREFA_PADRAO ADD CONSTRAINT R_GRUPO_PROD__TAREFA_PADRAO FOREIGN KEY (NU_GRUPO_PRODUTIVIDADE) REFERENCES GRUPO_PRODUTIVIDADE_SISAT ON DELETE SET NULL;
ALTER TABLE TAREFA_PADRAO ADD CONSTRAINT R_ENTIDADE__TAREFA_PADRAO FOREIGN KEY (CO_ENTIDADE_RESPONSAVEL) REFERENCES ENTIDADES;
ALTER TABLE POSICAO_CONTRATO ADD CONSTRAINT R_POSICAO_CONTRATO_SISAT FOREIGN KEY (NU_OCORRENCIA) REFERENCES OCORRENCIA_SISAT ON DELETE CASCADE;
ALTER TABLE DEPENDENCIA_TAREFA_PADRAO ADD CONSTRAINT R_289 FOREIGN KEY (CO_TAREFA_PADRAO) REFERENCES TAREFA_PADRAO;
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT R_OCORRENCIA_SISAT_STATUS FOREIGN KEY (CO_STATUS) REFERENCES STATUS;
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT R_OCORRENCIA_SISAT_ENTIDADES FOREIGN KEY (COD_ENT) REFERENCES ENTIDADES;
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT R_OCORRENCIA_SISAT_TAR_PADRAO FOREIGN KEY (CO_TAREFA_PADRAO) REFERENCES TAREFA_PADRAO;
ALTER TABLE PROJETO ADD CONSTRAINT R_IMOVEL_TERRENO_PROJETO FOREIGN KEY (NU_IMOVEL) REFERENCES IMOVEL_TERRENO;
ALTER TABLE SUBPROGRAMA ADD CONSTRAINT R_PROGRAMA_SUBPROGRAMA FOREIGN KEY (NU_PROGRAMA) REFERENCES PROGRAMA ON DELETE CASCADE;
ALTER TABLE OBRA ADD CONSTRAINT R_PROJETO_OBRA FOREIGN KEY (NU_PROJETO) REFERENCES PROJETO ON DELETE SET NULL;
ALTER TABLE OBRA ADD CONSTRAINT R_SUBPROGRAMA_OBRA FOREIGN KEY (NU_PROGRAMA, CO_SUBPROGRAMA) REFERENCES SUBPROGRAMA ON DELETE SET NULL;
ALTER TABLE CONTRATO_OBRA ADD CONSTRAINT R_FONTE_RECURSO_CONTRATO_OBRA FOREIGN KEY (CO_RECURSO) REFERENCES FONTE_RECURSO;
ALTER TABLE CONTRATO_OBRA ADD CONSTRAINT R_FORNECEDOR_CONTRATO_OBRA FOREIGN KEY (NU_FORNECEDOR) REFERENCES FORNECEDOR ON DELETE SET NULL;
ALTER TABLE CONTRATO_OBRA ADD CONSTRAINT R_OBRA_CONTRATO_OBRA FOREIGN KEY (NU_OBRA) REFERENCES OBRA ON DELETE CASCADE;
ALTER TABLE FATURA ADD CONSTRAINT R_CONTRATO_OBRA_FATURA FOREIGN KEY (NU_CONTRATO) REFERENCES CONTRATO_OBRA ON DELETE CASCADE;
ALTER TABLE PAGAMENTO_FATURA ADD CONSTRAINT R_FATURA_PAGAMENTO_FATURA FOREIGN KEY (NU_FATURA) REFERENCES FATURA ON DELETE CASCADE;
ALTER TABLE ITEM_FATURA ADD CONSTRAINT R_FATURA_ITEM_FATURA FOREIGN KEY (NU_FATURA) REFERENCES FATURA ON DELETE CASCADE;
ALTER TABLE PROJETO_BLOQUEADO ADD CONSTRAINT R_PROJETO_PROJETO_BLOQUEADO FOREIGN KEY (NU_PROJETO) REFERENCES PROJETO ON DELETE CASCADE;
ALTER TABLE RUA_PROJETO ADD CONSTRAINT R_PROJETO_RUA_PROJETO FOREIGN KEY (NU_PROJETO) REFERENCES PROJETO ON DELETE CASCADE;
ALTER TABLE CONFRONTACAO_RUA ADD CONSTRAINT R_RUA_PROJETO_CONFRONTACAO_RUA FOREIGN KEY (NU_PROJETO, NU_RUA) REFERENCES RUA_PROJETO ON DELETE CASCADE;
ALTER TABLE LOTE_PROJETO ADD CONSTRAINT R_PROJETO_LOTE_PROJETO FOREIGN KEY (NU_PROJETO) REFERENCES PROJETO ON DELETE CASCADE;
ALTER TABLE CONSTRUCAO_PROJETO ADD CONSTRAINT R_PROJETO_CONSTRUCAO_PROJETO FOREIGN KEY (NU_PROJETO) REFERENCES PROJETO ON DELETE CASCADE;
ALTER TABLE INCLUSAO_PREDIAL ADD CONSTRAINT R_LOTE_PROJ_INC_PRED FOREIGN KEY (NU_PROJETO, NU_LOTE, NU_QUADRA) REFERENCES LOTE_PROJETO ON DELETE CASCADE;
ALTER TABLE APROVACAO_PROJETO ADD CONSTRAINT R_APROVACAO_PROJETO_PROJETO FOREIGN KEY (NU_PROJETO) REFERENCES PROJETO ON DELETE CASCADE;
ALTER TABLE PENDENCIA_APROVACAO ADD CONSTRAINT R_PROJETO_PENDENCIA_APROVACAO FOREIGN KEY (NU_PROJETO) REFERENCES PROJETO ON DELETE CASCADE;
ALTER TABLE HISTORICO_PROJETO ADD CONSTRAINT R_PROJETO_HISTORICO_PROJETO FOREIGN KEY (NU_PROJETO) REFERENCES PROJETO ON DELETE CASCADE;
ALTER TABLE HISTORICO_IMOVEL ADD CONSTRAINT R_IMOVEL_TERRENO_HISTORICO_IMO FOREIGN KEY (NU_IMOVEL) REFERENCES IMOVEL_TERRENO ON DELETE CASCADE;
ALTER TABLE IMOVEL_BLOQUEADO ADD CONSTRAINT R_IMOVEL_TERRENO_IMOVEL_BLOQUE FOREIGN KEY (NU_IMOVEL) REFERENCES IMOVEL_TERRENO ON DELETE CASCADE;
ALTER TABLE AQUISICAO_IMOVEL ADD CONSTRAINT R_IMOVEL_TERRENO_AQUISICAO_IMO FOREIGN KEY (NU_IMOVEL) REFERENCES IMOVEL_TERRENO ON DELETE CASCADE;
ALTER TABLE REGISTRO_GERAL_IMOVEL ADD CONSTRAINT R_IMOVEL_TERRENO_REGISTRO_GERA FOREIGN KEY (NU_IMOVEL) REFERENCES IMOVEL_TERRENO ON DELETE CASCADE;
ALTER TABLE IMAGEM_DOCUMENTO_RGI ADD CONSTRAINT R_REGISTRO_GERAL_IMOVEL_IMAGEM FOREIGN KEY (NU_IMOVEL) REFERENCES REGISTRO_GERAL_IMOVEL ON DELETE CASCADE;
ALTER TABLE FONTE_RECURSO_PAGAMENTO ADD CONSTRAINT R_IMOVEL_TERRENO_FONTE_RECURSO FOREIGN KEY (NU_IMOVEL) REFERENCES IMOVEL_TERRENO ON DELETE CASCADE;
ALTER TABLE GRAVAME ADD CONSTRAINT R_IMOVEL_TERRENO_GRAVAME FOREIGN KEY (NU_IMOVEL) REFERENCES IMOVEL_TERRENO ON DELETE CASCADE;
ALTER TABLE TRIBUTO_IMOVEL ADD CONSTRAINT R_TIPO_TRIBUTO_TRIBUTO_IMOVEL FOREIGN KEY (CO_TRIBUTO) REFERENCES TIPO_TRIBUTO;
ALTER TABLE TRIBUTO_IMOVEL ADD CONSTRAINT R_IMV_TERRENO_TRIB_IMV FOREIGN KEY (NU_IMOVEL) REFERENCES IMOVEL_TERRENO ON DELETE CASCADE;
ALTER TABLE DOCUMENTO_CIP ADD CONSTRAINT R_PROJETO_DOCUMENTO_CIP FOREIGN KEY (NU_PROJETO) REFERENCES PROJETO ON DELETE CASCADE;
ALTER TABLE DOCUMENTO_CIP ADD CONSTRAINT R_USUARIO_DOCUMENTO_CIP FOREIGN KEY (CO_USUARIO_ENTREGOU) REFERENCES USUARIO;
ALTER TABLE DOCUMENTO_CIP ADD CONSTRAINT R_CONTROLEVERSAO_DOC_CIP_MERGE FOREIGN KEY (NU_VERSAO_COM_MERGE, ID_DOC_COM_MERGE) REFERENCES CONTROLEVERSAO;
ALTER TABLE DOCUMENTO_CIP ADD CONSTRAINT R_CONTROLEVERSAO_DOCUMENTO_CIP FOREIGN KEY (NU_VERSAO_SEM_MERGE, ID_DOC_SEM_MERGE) REFERENCES CONTROLEVERSAO;
ALTER TABLE CONFIGURACAO_USUARIO ADD CONSTRAINT R_USARIO_CONFIGURACAO_USUARIO FOREIGN KEY (USUARIO) REFERENCES USUARIO ON DELETE CASCADE;
ALTER TABLE CAMPO_EXPRESSAO_SIG_CONSULTA ADD CONSTRAINT R_FK_CAMPO_EXPR_SIG FOREIGN KEY (CO_CAMPO) REFERENCES CAMPO_EXPRESSAO_SIG;
ALTER TABLE TRAMITE_RNV ADD CONSTRAINT R_TRAMITE_RNV_RESP_CEF_RNV FOREIGN KEY (CO_RESP_CEF) REFERENCES RESP_CEF_RNV;
ALTER TABLE TRAMITE_RNV ADD CONSTRAINT R_TRAMITE_RNV_RESP_AGENTE_RNV FOREIGN KEY (CO_RESP_AGENTE) REFERENCES RESP_AGENTE_RNV;
ALTER TABLE SEGURADORA_MATERIAL_CONSTRUCAO ADD CONSTRAINT R_MAT_CONSTR_SEG_MAT_CONSTR FOREIGN KEY (CO_MATERIAL_CONSTRUCAO) REFERENCES MATERIAL_CONSTRUCAO;
ALTER TABLE COTACAO ADD CONSTRAINT R_ATENDIMENTO_COTACAO FOREIGN KEY (NU_ATENDIMENTO) REFERENCES ATENDIMENTO ON DELETE CASCADE;
ALTER TABLE COTACAO ADD CONSTRAINT R_FORNECEDOR_COTACAO FOREIGN KEY (CO_FORNECEDOR_VENCEDOR) REFERENCES FORNECEDOR_SACRE;
ALTER TABLE COTACAO_FORNECEDOR ADD CONSTRAINT R_FORN_COTACAO_FORN FOREIGN KEY (CO_FORNECEDOR) REFERENCES FORNECEDOR_SACRE ON DELETE CASCADE;
ALTER TABLE COTACAO_FORNECEDOR ADD CONSTRAINT R_COTACAO_COTACAO_FORN FOREIGN KEY (NU_ATENDIMENTO, NU_COTACAO) REFERENCES COTACAO ON DELETE CASCADE;
ALTER TABLE ITEM_COTACAO ADD CONSTRAINT R_COTACAO_FORN_ITEM_COTACAO FOREIGN KEY (NU_ATENDIMENTO, NU_COTACAO, CO_FORNECEDOR) REFERENCES COTACAO_FORNECEDOR ON DELETE CASCADE;
ALTER TABLE ITEM_COTACAO ADD CONSTRAINT R_MATERIAL_CONSTR_ITEM_CONSTR FOREIGN KEY (CO_MATERIAL_CONSTRUCAO) REFERENCES MATERIAL_CONSTRUCAO;
ALTER TABLE MATERIAL_NECESSARIO ADD CONSTRAINT R_MAT_CONST_MATERIAL_NECES FOREIGN KEY (CO_MATERIAL_CONSTRUCAO) REFERENCES MATERIAL_CONSTRUCAO;
ALTER TABLE CAMPOS_RET ADD CONSTRAINT XFKCAMPOS_RET FOREIGN KEY (CO_RET_GEN) REFERENCES RETORNO_GENERICO ON DELETE CASCADE;
ALTER TABLE CAMPOS_LASER ADD CONSTRAINT XFKCAMPOS_LASER FOREIGN KEY (CO_LASER_GEN) REFERENCES LASER_GENERICO ON DELETE CASCADE;
ALTER TABLE CAMPOS_REM ADD CONSTRAINT XFKCAMPOS_REM FOREIGN KEY (CO_REM_GEN,NU_REGISTRO) REFERENCES REMESSA_GENERICA ON DELETE CASCADE;
ALTER TABLE CAMPOS_REM_SPC ADD CONSTRAINT XFKCAMPOS_REM_SPC FOREIGN KEY (CO_REM_GEN,NU_REGISTRO) REFERENCES REMESSA_GENERICA_SPC ON DELETE CASCADE;
ALTER TABLE CAMPOS_RET_SPC ADD CONSTRAINT XFKCAMPOS_RET_SPC FOREIGN KEY (CO_RET_GEN) REFERENCES RETORNO_GENERICO_SPC ON DELETE CASCADE;
ALTER TABLE SETOR_EXECUTOR_TAREFA ADD CONSTRAINT R_USUARIO_SETOR_EXECUTOR FOREIGN KEY (USUARIO) REFERENCES USUARIO ON DELETE CASCADE;
ALTER TABLE SETOR_EXECUTOR_TAREFA ADD CONSTRAINT R_TAREFA_PADRAO_SETOR_EXECUTOR FOREIGN KEY (CO_TAREFA_PADRAO) REFERENCES TAREFA_PADRAO ON DELETE CASCADE;
ALTER TABLE VARIAVEL_TAREFA_PADRAO ADD CONSTRAINT R_TAREFA_PADRAO__VARIAVEL FOREIGN KEY (CO_TAREFA_PADRAO) REFERENCES TAREFA_PADRAO ON DELETE CASCADE;
ALTER TABLE VARIAVEL_TAREFA_PADRAO ADD CONSTRAINT R_VAR_TAREFA_VAR_TAREFA_PADRAO FOREIGN KEY (NU_VARIAVEL) REFERENCES VARIAVEL_TAREFA;
ALTER TABLE HISTORICO_TEXTO_OCORRENCIA ADD CONSTRAINT R_OCORRENCIA_SISAT__HISTORICO FOREIGN KEY (NU_OCORRENCIA) REFERENCES OCORRENCIA_SISAT ON DELETE CASCADE;
ALTER TABLE CODIGOS_OPERACOES ADD CONSTRAINT R_USUARIO_RESP__CODIGOS_OPER FOREIGN KEY (CO_USUARIO_RESPONSAVEL_OPER) REFERENCES USUARIO ON DELETE SET NULL;
ALTER TABLE TAXAS_OPERACOES ADD CONSTRAINT R_TAXAS_OPERACOES_CO_OPERACAO FOREIGN KEY (CO_OPERACAO) REFERENCES CODIGOS_OPERACOES ON DELETE CASCADE;
ALTER TABLE DOC_ACORDO ADD CONSTRAINT XFKDOC_ACORDO FOREIGN KEY (CO_ACORDO) REFERENCES CONFIG_PROG_REC_CRED ON DELETE CASCADE;
ALTER TABLE DIFERENCA_REIMPLANTACAO ADD CONSTRAINT XPK2DIFERENCA_REIMPLANTACAO FOREIGN KEY (NU_OCORRENCIA) REFERENCES OCORRENCIA;
ALTER TABLE TAREFA_PERIODICA ADD CONSTRAINT r_responsavel__tarefa_period FOREIGN KEY (CO_USUARIO_RESPONSAVEL) REFERENCES USUARIO;
ALTER TABLE TAREFA_PERIODICA ADD CONSTRAINT R_SETOR__TAREFA_PERIODICA FOREIGN KEY (COD_ENT, CO_SETOR_RESPONSAVEL) REFERENCES SETOR;
ALTER TABLE TAREFA_PERIODICA ADD CONSTRAINT R_TAR_PERIODICA__TAR_PADRAO FOREIGN KEY (CO_TAREFA_PADRAO) REFERENCES TAREFA_PADRAO;
ALTER TABLE ATENDIMENTO_MIP ADD CONSTRAINT R_ATENDIMENTO__ATENDIMENTO_MIP FOREIGN KEY (NU_ATENDIMENTO) REFERENCES ATENDIMENTO ON DELETE CASCADE;
ALTER TABLE PENDENCIA_CRIACAO_TAREFA ADD CONSTRAINT R_TAR_ORIGEM__PEND_CRIACAO FOREIGN KEY (CO_TAREFA_PADRAO_A_CRIAR) REFERENCES TAREFA_PADRAO ON DELETE CASCADE;
ALTER TABLE PENDENCIA_CRIACAO_TAREFA ADD CONSTRAINT R_OCOR_ORIGEM__PEND_CRIACAO FOREIGN KEY (NU_OCORRENCIA_ORIGEM)REFERENCES OCORRENCIA_SISAT ON DELETE CASCADE;
ALTER TABLE PENDENCIA_CRIACAO_TAREFA ADD CONSTRAINT R_TAR_PEND__PEND_CRIACAO FOREIGN KEY (CO_TAREFA_PADRAO_PENDENTE) REFERENCES TAREFA_PADRAO ON DELETE CASCADE;
ALTER TABLE PENDENCIA_CRIACAO_TAREFA ADD CONSTRAINT R_OCOR_INICIAL__PEND_CRIACAO FOREIGN KEY (NU_OCORRENCIA_INICIAL) REFERENCES OCORRENCIA_SISAT ON DELETE CASCADE;
ALTER TABLE ACAO_OCORRENCIA_SISAT ADD CONSTRAINT R_USUARIO__ACAO_OCORRENCIA FOREIGN KEY (CO_GESTOR) REFERENCES USUARIO;
ALTER TABLE ACAO_OCORRENCIA_SISAT ADD CONSTRAINT R_ACAO__ACAO_OCORRENCIA FOREIGN KEY (NU_ACAO_TAREFA)REFERENCES ACAO_TAREFA;
ALTER TABLE ACAO_OCORRENCIA_SISAT ADD CONSTRAINT R_OCORRENCIA__ACAO_OCORRENCIA FOREIGN KEY (NU_OCORRENCIA) REFERENCES OCORRENCIA_SISAT ON DELETE CASCADE;
ALTER TABLE CONFIG_TAREFA_COBRANCA ADD CONSTRAINT R_TAR_PADRAO_CONFIG_COBRANCA FOREIGN KEY (CO_TAREFA_PADRAO) REFERENCES TAREFA_PADRAO;
ALTER TABLE CONFIG_TAREFA_COBRANCA ADD CONSTRAINT R_CONFIG_COBRANCA_SISTARQ FOREIGN KEY (ID_SCRIPT_COBRANCA) REFERENCES SISTARQ;
ALTER TABLE ACAO_TAREFA_PADRAO ADD CONSTRAINT R_TAREFA_PADRAO_ACAO_TAREFA FOREIGN KEY (CO_TAREFA_PADRAO) REFERENCES TAREFA_PADRAO ON DELETE CASCADE;
ALTER TABLE ACAO_TAREFA_PADRAO ADD CONSTRAINT R_ACAO__ACAO_TAREFA_PADRAO FOREIGN KEY (NOME) REFERENCES ACAO ON DELETE CASCADE;
ALTER TABLE REQUISITOS_ACAO_TAREFA_PADRAO ADD CONSTRAINT R_VARIAVEL_REQ_TAREFA_PADRAO FOREIGN KEY (CO_TAREFA_PADRAO, NU_VARIAVEL) REFERENCES VARIAVEL_TAREFA_PADRAO ON DELETE CASCADE;
ALTER TABLE REQUISITOS_ACAO_TAREFA_PADRAO ADD CONSTRAINT R_REQ_ACAO_ACAO_TAR_PADRAO FOREIGN KEY (CO_TAREFA_PADRAO, NOME) REFERENCES ACAO_TAREFA_PADRAO ON DELETE CASCADE;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USUA_CANCELAMENTO__OPERACAO FOREIGN KEY (CO_USUARIO_CANCELAMENTO) REFERENCES USUARIO;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_CESSIO_OPERACAO_CREDITO FOREIGN KEY (CO_CESSIONARIO_CREDITO) REFERENCES ENTIDADES;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USU_PARECER_JUR__OPERACAO FOREIGN KEY (CO_USUARIO_PARECER_JURIDICO) REFERENCES USUARIO;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USU_PARECER_TEC__OPERACAO FOREIGN KEY (CO_USUARIO_PARECER_TECNICO) REFERENCES USUARIO;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USU_REGISTRO__OPERACAO FOREIGN KEY (CO_USUARIO_REGISTRO) REFERENCES USUARIO;
ALTER TABLE RECEITA_COMERCIALIZACAO ADD CONSTRAINT R_RECEITA_COMERCIALIZACAO FOREIGN KEY (CO_TIPO_RECEITA) REFERENCES TIPO_RECEITA_ORIGINACAO (CO_TIPO_RECEITA);
ALTER TABLE TIPO_OPERACAO ADD CONSTRAINT R_ENTIDADE__TIPO_OPERACAO FOREIGN KEY (CO_CESSIONARIO_CREDITO) REFERENCES ENTIDADES ON DELETE SET NULL;
ALTER TABLE TIPO_OPERACAO ADD CONSTRAINT R_ID_JURIDICO__TIPO_OPERACAO FOREIGN KEY (ID_PARECER_JURIDICO) REFERENCES SISTARQ ON DELETE SET NULL;
ALTER TABLE TIPO_OPERACAO ADD CONSTRAINT R_ID_REGISTRO__TIPO_OPERACAO FOREIGN KEY (ID_PARECER_REGISTRO) REFERENCES SISTARQ ON DELETE SET NULL;
ALTER TABLE TIPO_OPERACAO ADD CONSTRAINT R_ID_TECNICO__TIPO_OPERACAO FOREIGN KEY (ID_PARECER_TECNICO) REFERENCES SISTARQ ON DELETE SET NULL;
ALTER TABLE FAIXA_TAXA_ADMINISTRACAO ADD CONSTRAINT R_TIPO_OPERACAO__FAIXA_TX_ADM FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO ON DELETE SET NULL;
ALTER TABLE SERIE_TIPO_OPERACAO ADD CONSTRAINT R_TIPO_OPERACAO__SERIE_TP_OPER FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO ON DELETE CASCADE;
ALTER TABLE VARIAVEL_ORIGINACAO ADD CONSTRAINT R_TIPO_OPERACAO__VARIAVEL FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO ON DELETE SET NULL;
ALTER TABLE ENTIDADES ADD CONSTRAINT R_ENTIDADE_SUPERIOR FOREIGN KEY (CO_ENTIDADE_SUPERIOR) REFERENCES ENTIDADES;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USUARIO_CAD__OPERACAO FOREIGN KEY (CO_USUARIO_CADASTRAMENTO) REFERENCES USUARIO;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_TIPO_OPERACAO_OPERACAO FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USUARIO_CORRETOR_OPERACAO FOREIGN KEY (CO_CORRETOR) REFERENCES USUARIO;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_OPERACAO__SETOR FOREIGN KEY (COD_ENT_CORRETAGEM, CO_UNIDADE_CORRETAGEM) REFERENCES SETOR;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_ENT_SUPERIOR__OPERACAO FOREIGN KEY (COD_ENT_SUPERVISOR) REFERENCES ENTIDADES;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_OPERACAO__PRETENDENTE FOREIGN KEY (NU_PRETENDENTE) REFERENCES PRETENDENTE ON DELETE CASCADE;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_FASE_OPERACAO__OPERACAO Foreign key (NU_FASE_ATUAL) References FASE_OPERACAO (NU_FASE_OPERACAO);
ALTER TABLE IMOVEL_OPERACAO ADD CONSTRAINT R_OPERACAO_CREDITO__IMOVEL FOREIGN KEY (NU_OPERACAO) REFERENCES OPERACAO_CREDITO ON DELETE CASCADE;
ALTER TABLE CONFIGURACAO_ORIGINACAO ADD CONSTRAINT R_TAR_PADRAO_CONFIG_ORIGINACAO FOREIGN KEY (CO_TAREFA_SIMULACAO) REFERENCES TAREFA_PADRAO;
ALTER TABLE CONFIGURACAO_ORIGINACAO ADD CONSTRAINT R_TAR_ENVIO__CONF_ORIG FOREIGN KEY (CO_TAREFA_ENVIO_PROPOSTA) REFERENCES TAREFA_PADRAO;
ALTER TABLE CONFIGURACAO_ORIGINACAO ADD CONSTRAINT R_SISTARQ_CONFIG_ORIGINACAO FOREIGN KEY (ID_EMAIL_SIMULACAO) REFERENCES SISTARQ;
ALTER TABLE CONFIGURACAO_ORIGINACAO ADD CONSTRAINT R_SISTARQ2_CONFIG_ORIGINACAO FOREIGN KEY (ID_EMAIL_PROPOSTA) REFERENCES SISTARQ;
ALTER TABLE CONFIGURACAO_ORIGINACAO ADD CONSTRAINT R_FASE__CONFIG_ORIGINACAO FOREIGN KEY (NU_FASE_CANCELAMENTO) REFERENCES FASE_OPERACAO;
ALTER TABLE CONFIGURACAO_ORIGINACAO ADD CONSTRAINT R_TAR_INDICACAO_CONF_ORIG FOREIGN KEY (CO_TAREFA_INDICACAO) REFERENCES TAREFA_PADRAO;
ALTER TABLE TIPO_OPERACAO ADD CONSTRAINT R_GRUPO_TIPO_OPER__TIPO_OPER FOREIGN KEY (CO_GRUPO_TIPO_OPERACAO) REFERENCES GRUPO_TIPO_OPERACAO;
ALTER TABLE UNIDADE_CAIXA ADD CONSTRAINT R_UNIDADE_CAIXA FOREIGN KEY (CO_TP_UNIDADE) REFERENCES TIPO_UNIDADE_CAIXA;
ALTER TABLE STATUS_FINALIZA_TAREFA_DOC ADD CONSTRAINT R_STATUS_FIN_TAREFA_DOC__02 FOREIGN KEY (NU_GRUPO_DOCUMENTO, NU_DOCUMENTO_GRUPO_DOC) REFERENCES DOCUMENTO_GRUPO_DOCUMENTO;
ALTER TABLE DOCUMENTO_GRUPO_DOCUMENTO ADD CONSTRAINT R_TIPO_OPER__DOC_GRUPO_DOC FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO;
ALTER TABLE DOCUMENTO_GRUPO_DOCUMENTO ADD CONSTRAINT R_GRUPO_DOC__DOC_GRUPO FOREIGN KEY (NU_GRUPO_DOCUMENTO) REFERENCES GRUPO_DOCUMENTO ON DELETE CASCADE;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_GRUPO_DOC__DOC_OPERACAO FOREIGN KEY (NU_GRUPO_DOCUMENTO) REFERENCES GRUPO_DOCUMENTO;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_SISTARQ__DOC_OPERACAO FOREIGN KEY (ID) REFERENCES SISTARQ;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_PESSOA_PRET__DOC_OPERACAO FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_USUARIO_PAREC__DOC_OPERACAO FOREIGN KEY (CO_USUARIO_PARECER) REFERENCES USUARIO;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_USUARIO_RECEB__DOC_OPERACAO FOREIGN KEY (CO_USUARIO_RECEBIMENTO) REFERENCES USUARIO;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_OPERACAO__DOC_OPERACAO FOREIGN KEY (NU_OPERACAO) REFERENCES OPERACAO_CREDITO ON DELETE CASCADE;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_DOC_GRUPO__DOC_OPERACAO FOREIGN KEY (NU_GRUPO_DOCUMENTO, NU_DOCUMENTO_GRUPO_DOC) REFERENCES DOCUMENTO_GRUPO_DOCUMENTO;
ALTER TABLE OUTRA_RENDA_PRETENDENTE ADD CONSTRAINT R_OUTRA_RENDA__PESSOA_PRET FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE PESSOA_EXPOSICAO_POLITICA ADD CONSTRAINT R_PESSOA_PRET__EXP_POLITICA FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE DADOS_AUX_RENDA_PRETENDENTE ADD CONSTRAINT R_PESSOA_PRET__DADOS_AUX_PRET FOREIGN KEY (NU_PESSOA,NU_PRETENDENTE) REFERENCES PESSOA_PRETENDENTE ON DELETE CASCADE;
ALTER TABLE HISTORICO_OPERACAO ADD CONSTRAINT R_USUARIO_HISTORICO_OPERACAO FOREIGN KEY (CO_USUARIO_FASE) REFERENCES USUARIO;
ALTER TABLE HISTORICO_OPERACAO ADD CONSTRAINT R_FASE__HISTORICO_OPERACAO Foreign key (NU_FASE_OPERACAO) References FASE_OPERACAO (NU_FASE_OPERACAO);
ALTER TABLE HISTORICO_OPERACAO ADD CONSTRAINT R_OPERACAO__HISTORICO_OPERACAO FOREIGN KEY (NU_OPERACAO) REFERENCES OPERACAO_CREDITO ON DELETE CASCADE;
ALTER TABLE TIPO_REMUNERACAO ADD CONSTRAINT R_ENTIDADES_TIPO_REMUNERACAO FOREIGN KEY (COD_ENT) REFERENCES ENTIDADES ON DELETE CASCADE;
ALTER TABLE TIPO_REMUNERACAO ADD CONSTRAINT R_TIPO_OPERACAO__REMUNERACAO FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO ON DELETE CASCADE;
ALTER TABLE PRODOPER ADD CONSTRAINT XFK1_PRODOPER FOREIGN KEY (CO_ROTINA_ANTERIOR) REFERENCES PRODOPER;
ALTER TABLE MOV_LIB_ORIGINACAO ADD CONSTRAINT XFK1_MOV_LIB_ORIGINACAO FOREIGN KEY (CO_TIPO_LIBERACAO) REFERENCES TIPO_LIBERACAO_ORIGINACAO;
ALTER TABLE MOV_LIB_ORIGINACAO ADD CONSTRAINT XFK2_MOV_LIB_ORIGINACAO FOREIGN KEY (CO_TIPO_MOVIMENTACAO) REFERENCES CONF_MOV_LIBERACAO;
ALTER TABLE MOTIVO_EMPRESTIMO ADD CONSTRAINT XFK1_MOTIVO_EMPRESTIMO FOREIGN KEY (NU_OPERACAO) REFERENCES OPERACAO_CREDITO;
ALTER TABLE MOTIVO_EMPRESTIMO ADD CONSTRAINT XFK2_MOTIVO_EMPRESTIMO FOREIGN KEY (CO_MOTIVO_EMPRESTIMO) REFERENCES TABMOTIVO_EMPRESTIMO;
ALTER TABLE PASTA_DOCUMENTOS ADD CONSTRAINT R_OPERACAO__PASTA_DOC FOREIGN KEY (NU_OPERACAO) REFERENCES OPERACAO_CREDITO;
ALTER TABLE PASTA_DOCUMENTOS ADD CONSTRAINT R_OCORRENCIA__PASTA_DOC FOREIGN KEY (NU_OCORRENCIA) REFERENCES OCORRENCIA_SISAT;
ALTER TABLE SENHA_ATENDIMENTO_SISAT ADD CONSTRAINT R_TAREFA_PADRAO__SENHA_ATEND FOREIGN KEY (CO_TAREFA_PADRAO) REFERENCES TAREFA_PADRAO;
ALTER TABLE SENHA_ATENDIMENTO_SISAT ADD CONSTRAINT R_OCORRENCIA__SENHA_ATEND FOREIGN KEY (NU_OCORRENCIA) REFERENCES OCORRENCIA_SISAT;
ALTER TABLE TRAMITACAO_FCVS ADD CONSTRAINT R_TRAMITACAO_FCVS FOREIGN KEY (CO_TIPO_TRAMITACAO_FCVS) REFERENCES TIPO_TRAMITACAO_FCVS;
ALTER TABLE USUARIO_COMISSAO ADD CONSTRAINT R_USUARIO_COMISSAO FOREIGN KEY (CO_USUARIO) REFERENCES USUARIO(USUARIO);
ALTER TABLE CONFIG_COMISSAO_USUARIO ADD CONSTRAINT R_CONFIG_COMISSAO_USUARIO FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO(CO_TIPO_OPERACAO);
ALTER TABLE CONFIG_COMISSAO_USUARIO ADD CONSTRAINT R_CONFIG_USUARIO_TIPOLIB FOREIGN KEY (CO_TIPODESPIMV) REFERENCES TIPO_LIBERACAO_ORIGINACAO(CO_TIPO_LIBERACAO);
ALTER TABLE CONFIG_COMISSAO_USUARIO ADD CONSTRAINT R_CONFIG_USUARIO_PERFIL FOREIGN KEY (CO_PERFIL) REFERENCES PERFIL(COD_PERFIL);
ALTER TABLE CONFIG_COMISSAO_ENTIDADES ADD CONSTRAINT R_CONFIG_COMISSAO_ENTIDADES FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO(CO_TIPO_OPERACAO);
ALTER TABLE CONFIG_COMISSAO_ENTIDADES ADD CONSTRAINT R_CONFIG_ENTIDADES_TIPOLIB FOREIGN KEY (CO_TIPODESPIMV) REFERENCES TIPO_LIBERACAO_ORIGINACAO(CO_TIPO_LIBERACAO);
ALTER TABLE PORTABILIDADE_CLIENTE ADD CONSTRAINT XFK1PORTABILIDADE_CLIENTE FOREIGN KEY (SEQPORTABILIDADE) REFERENCES PORTABILIDADE ON DELETE CASCADE;
ALTER TABLE TRAMITACAO_PORTABILIDADE ADD CONSTRAINT XFK1TRAMITACAO_PORTABILIDADE FOREIGN KEY (SEQPORTABILIDADE) REFERENCES PORTABILIDADE ON DELETE CASCADE;
ALTER TABLE PARECER_OPERACAO ADD CONSTRAINT R_USUARIO_PARECER_OPERACAO FOREIGN KEY (CO_USUARIO_PARECER) REFERENCES USUARIO;
ALTER TABLE PARECER_OPERACAO ADD CONSTRAINT R_OPERACAO__PARECER_OPERACAO FOREIGN KEY (NU_OPERACAO) REFERENCES OPERACAO_CREDITO ON DELETE CASCADE;
ALTER TABLE TIPO_ATENDIMENTO ADD CONSTRAINT R_TAR_PADRAO_TIPO_ATENDIMENTO FOREIGN KEY (CO_TAREFA_PADRAO) REFERENCES TAREFA_PADRAO;
ALTER TABLE TRAVA_TIPO_ATENDIMENTO ADD CONSTRAINT R_DOC_TIPO_ATENDIMENTO FOREIGN KEY (NU_TIPO_ATENDIMENTO,NU_TIPO_DOCUMENTO) REFERENCES DOCUMENTO_TIPO_ATENDIMENTO;
ALTER TABLE DOCUMENTO_OCORRENCIA_SISAT ADD CONSTRAINT R_DOC_TP_AT__DOC_OCORR_SISAT FOREIGN KEY (NU_TIPO_ATENDIMENTO,NU_TIPO_DOCUMENTO) REFERENCES DOCUMENTO_TIPO_ATENDIMENTO;
ALTER TABLE SEGURADORA_TIPO_OPERACAO ADD CONSTRAINT R_TIPO_OPERACAO__SEG_TP_OPER FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO ON DELETE CASCADE;
ALTER TABLE EMAIL_ANEXO ADD CONSTRAINT FK_EMAIL_ANEXO FOREIGN KEY (NU_EMAIL) REFERENCES EMAIL_A_ENVIAR;
ALTER TABLE FAIXA_COBERTURA_APOLICE ADD CONSTRAINT FK_FAIXA_COBERTURA_APOLICE1 FOREIGN KEY (CODAPOLICE) REFERENCES TABAPOLICE ON DELETE CASCADE;
ALTER TABLE ANEXO_CONFIG_MODELOS_CONTRATO ADD CONSTRAINT XFK1_ANEXO_CONFIG FOREIGN KEY (CO_CONFIGURACAO) REFERENCES CONFIG_MODELOS_CONTRATO;
ALTER TABLE ANEXO_CONFIG_MODELOS_CONTRATO ADD CONSTRAINT XFK2_ANEXO_CONFIG FOREIGN KEY (NU_GRUPO_DOCUMENTO) REFERENCES GRUPO_DOCUMENTO;
ALTER TABLE DOCUMENTO_A_ASSINAR ADD CONSTRAINT XFK1_DOCUMENTO_A_ASSINAR FOREIGN KEY (NU_OPERACAO, NU_DOCUMENTO) REFERENCES DOCUMENTO_OPERACAO (NU_OPERACAO, NU_DOCUMENTO) ON DELETE CASCADE;
ALTER TABLE ASSINATURA_DOCUMENTO ADD CONSTRAINT R_ASSIN_DOC__DOC_ASSINAR FOREIGN KEY (NU_ASSINATURA) REFERENCES DOCUMENTO_A_ASSINAR ON DELETE CASCADE;
ALTER TABLE SISTARQ_TEMPORARIO ADD CONSTRAINT XFK1_SISTARQ_TEMPORARIO FOREIGN KEY (ID) REFERENCES SISTARQ;
ALTER TABLE OPCAO_EVENTO_CHATBOT ADD CONSTRAINT R_OPCAO_EVENTO_CHATBOT__EVENTO FOREIGN KEY (CO_EVENTO) REFERENCES EVENTO_CHATBOT;
ALTER TABLE CARENCIA_TIPO_OPERACAO ADD CONSTRAINT R_TIPO_OPERACAO__CAR_TP_OPER FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO ON DELETE CASCADE;
ALTER TABLE TIPO_ENQUADRAMENTO_PRODUTO ADD CONSTRAINT R_TP_ENQUAD_PROD_TP_ENQUAD FOREIGN KEY (CO_ENQUADRAMENTO) REFERENCES TIPO_ENQUADRAMENTO;
ALTER TABLE TIPO_ENQUADRAMENTO_PRODUTO ADD CONSTRAINT R_TP_ENQUAD_PROD_PCT_PROD FOREIGN KEY (CO_PACOTE_PRODUTO) REFERENCES PACOTE_PRODUTO;
ALTER TABLE PARCELA_LOTE ADD CONSTRAINT XFK1_PARCELA_LOTE FOREIGN KEY (NU_LOTE) REFERENCES LOTE;
ALTER TABLE REG_CONTAMINACAO_CURA_CLIENTE ADD CONSTRAINT XFK1REGCONTCURACLIENTE FOREIGN KEY (NU_SEQ_FK) REFERENCES REGISTRO_CONTAMINACAO_CURA;
ALTER TABLE INDEXADOR_TP_OPERACAO ADD CONSTRAINT R_TIPO_OPERACAO__INDEX_TP_OPER FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO ON DELETE CASCADE;
ALTER TABLE CAMPO_PERDA_ANALISE_CRED ADD CONSTRAINT R_CO_CONDICAO_PERDA_ANALISE FOREIGN KEY (CO_CONDICAO_PERDA) REFERENCES CONDICAO_PERDA_ANALISE ON DELETE CASCADE;
ALTER TABLE IMOVEL_TIPO_OPERACAO ADD CONSTRAINT R_TIPO_OPERACAO__IMV_TP_OPER FOREIGN KEY (CO_TIPO_OPERACAO) REFERENCES TIPO_OPERACAO ON DELETE CASCADE;
ALTER TABLE IMOVEL_TIPO_OPERACAO ADD CONSTRAINT R_TIPOIMV__IMV_TP_OPER FOREIGN KEY (CO_TIPO_IMOVEL) REFERENCES TIPOIMV (TIPOIMV);
ALTER TABLE IMOVEL_TIPO_OPERACAO ADD CONSTRAINT R_TABIMVTIPO__IMV_TP_OPER FOREIGN KEY (CO_TIPO_IMOVEL_ZONEAMENTO) REFERENCES TIPOIMV (TIPOIMV);

-- -----------------------------------------------------------------------------
-- VERIFICAÇÃO 1: contagem total de FKs criadas no schema
-- (esperado: 232)
-- -----------------------------------------------------------------------------
SELECT COUNT(*) AS total_fks FROM pg_constraint WHERE contype = 'f';

-- -----------------------------------------------------------------------------
-- VERIFICAÇÃO 2: lista FKs em estado NOT VALID
-- (esperado: zero linhas - todas validadas na criação)
-- -----------------------------------------------------------------------------
SELECT conrelid::regclass AS tabela, conname AS constraint_name
FROM pg_constraint
WHERE contype = 'f' AND NOT convalidated
ORDER BY 1, 2;
