update acao set DESCRICAO = 'Simular Marco das Garantias - Alienação Estendida' where nome = 'WSIMULARCALCULODAOPERACAOALIENACAOESTENDIDA';
update empreendimentos set CODIGOCR = null where empreend = '117';
update empreendimentos_blocos set NO_BLOCO = 'UNICO' where co_empreendimento = '31003';
update fonema_pretendente set no_fonema = 'MOHIEDDIMAHMADALLOUCHE' where nu_pretendente = '000506587';
update fonema_pretendente set no_fonema = 'JHONNATTASRIBEIROQUEIROZ' where nu_pretendente = '000535219';
update fonema_pretendente set no_fonema = 'ANDERSOMLEONIENTSCH' where nu_pretendente = '000545601';
update funcao set DESCRICAO = 'Simular Marco das Garantias - Alienação Estendida' where codigo = '3560';
delete from scci_session where no_usuario = 'larissa.eleuterio' and dt_hora_solicitacao = '2026-03-13 12:10:08.1050';
delete from scci_session where no_usuario = 'larissa.eleuterio' and dt_hora_solicitacao = '2026-03-13 15:17:14.3590';
delete from documento_operacao where id = '110055';
delete from sistarq where id = '110055';
update log_eventos set NU_PRETENDENTE = null where co_log = '884668';
update log_eventos set NU_PRETENDENTE = null where co_log = '1037260';
update tablcobr set CIDBAN = 'SÃO PAULO' , ASSUNTO_EMAIL_1A_VIA = 'Emissao Mensal por Email' where lcobr = '3';
update tabmod_bacen set NO_MODALIDADE = 'Empréstimos Cartão de Crédito - compra, fatura parcelada ou saque financiado' where co_modalidade = '210';
update tabmov set DESCRICAO = 'Generico uso Int.' where codmov = '71';
update tipo_tramitacao_fcvs set NO_DESCRICAO = 'CONTRATOS COM ERROS DE CRÍTICA - RNV' where co_tipo_tramitacao_fcvs = '22';
update tipo_tramitacao_fcvs set NO_DESCRICAO = 'CONTRATOS COM TRANSFERÊNCIA DE TITULARIDADE - AGENTE CEDENTE' where co_tipo_tramitacao_fcvs = '33';
update tipo_tramitacao_fcvs set NO_DESCRICAO = 'CONTRATOS COM TRANSFERÊNCIA DE TITULARIDADE - AGENTE CESSIONÁRIO' where co_tipo_tramitacao_fcvs = '34';
update tipo_tramitacao_fcvs set NO_DESCRICAO = 'SITUAÇÃO DA DÍVIDA - CONTRATO EMPRÉSTIMO CAIXA' where co_tipo_tramitacao_fcvs = '45';
update tipo_tramitacao_fcvs set NO_DESCRICAO = 'CONTRATOS COM TÉRMINO DE ANÁLISE - REPROCESSADOS' where co_tipo_tramitacao_fcvs = '55';
update tipo_tramitacao_fcvs set NO_DESCRICAO = 'CONTRATOS COM TÉRMINO ANÁLISE - REPROCESSADOS - CONSOLIDADO (eventual)' where co_tipo_tramitacao_fcvs = '57';
update tipo_tramitacao_fcvs set NO_DESCRICAO = 'CONTRATOS COM TÉRMINO DE ANÁLISE - CONSOLIDADO (eventual)' where co_tipo_tramitacao_fcvs = '59';
update tipo_tramitacao_fcvs set NO_DESCRICAO = 'CONTRATOS EXISTENTES NO CADMUT - AGUARDANDO ACERTO' where co_tipo_tramitacao_fcvs = '73';
update tipo_tramitacao_fcvs set NO_DESCRICAO = 'ANALÍTICO DO TESOURO (CONTRATOS COM SALDO VAF3 E VAF4 P/ NOVAÇÃO - VALORES POS. EM 01/01/1997' where co_tipo_tramitacao_fcvs = '92';
commit;
