-- PKs, CHECK constraints e Indices das 10 tabelas grandes
-- Gerado em 2026-04-08

-- =============================================
-- Tabela: CONTROLEVERSAO
-- =============================================
ALTER TABLE CONTROLEVERSAO ADD PRIMARY KEY (VERSAO, ID);
CREATE INDEX R_CONTROLEVERSAO_SISTARQ ON CONTROLEVERSAO(ID);
CREATE INDEX AKCONTROLEVERSAOUSUARIO ON CONTROLEVERSAO( CO_USUARIO_IMPLANTACAO );
CREATE INDEX CONTROLEVERSAODATA ON CONTROLEVERSAO(ALT_DATA,ID);


-- =============================================
-- Tabela: PESSOA_PRETENDENTE
-- =============================================
ALTER TABLE PESSOA_PRETENDENTE ADD CONSTRAINT XPKPESSOA_PRETENDENTE PRIMARY KEY (NU_PESSOA,
              NU_PRETENDENTE);
CREATE INDEX XIF129PESSOA_PRETENDENTE ON PESSOA_PRETENDENTE(
       NU_PRETENDENTE);
CREATE INDEX ICPF_PESSOA_PRETENDENTE ON PESSOA_PRETENDENTE(NU_CPFCNPJ);
CREATE INDEX IDX_CO_MUNICIPIO ON PESSOA_PRETENDENTE(CO_MUNICIPIO, NU_PRETENDENTE);
CREATE INDEX IDX_NO_PESSOA_PRETENDENTE ON PESSOA_PRETENDENTE(NO_PESSOA);
CREATE INDEX IDX_NU_PRETENDENTE_PESSOA ON PESSOA_PRETENDENTE(NU_PRETENDENTE, NU_PESSOA);
CREATE INDEX R_PESSOA_PRINCIPAL ON PESSOA_PRETENDENTE(NU_PESSOA_PRINCIPAL, NU_PRETENDENTE);


-- =============================================
-- Tabela: OCORRENCIA
-- =============================================
ALTER TABLE OCORRENCIA ADD CONSTRAINT XPKOCORRENCIA PRIMARY KEY (NU_OCORRENCIA);


-- =============================================
-- Tabela: OCORRENCIA_SISAT
-- =============================================
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT MAIORQUEZERO CHECK (NU_OCORRENCIA > 0);
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT XPKOCORRENCIA_SISAT PRIMARY KEY (NU_OCORRENCIA);
CREATE INDEX R_ENTIDADE_OCORRENCIA_SISAT ON OCORRENCIA_SISAT(CO_ENTIDADE_EXECUCAO);
CREATE INDEX XIF202OCORRENCIA_SISAT ON OCORRENCIA_SISAT(NU_CONTRATO);
CREATE INDEX OCORRENCIA_SISATX18 on ocorrencia_sisat (CO_ENTIDADE_EXECUCAO DESC, DT_CADASTRAMENTO DESC);
CREATE INDEX XIF165OCORRENCIA_SISAT ON OCORRENCIA_SISAT(
       CO_TAREFA_PADRAO);
CREATE INDEX XIF166OCORRENCIA_SISAT ON OCORRENCIA_SISAT(
       CO_STATUS);
CREATE INDEX XIF170OCORRENCIA_SISAT ON OCORRENCIA_SISAT(
       CO_GESTOR);
CREATE INDEX XIF171OCORRENCIA_SISAT ON OCORRENCIA_SISAT(
       CO_USUARIO_CADASTRAMENTO);
CREATE INDEX XIF174OCORRENCIA_SISAT ON OCORRENCIA_SISAT(
       COD_ENT);
CREATE INDEX XIF244OCORRENCIA_SISAT ON OCORRENCIA_SISAT(
       NU_OCORRENCIA_ANTERIOR);
CREATE INDEX XAK_PROTOCOLO_SISAT ON OCORRENCIA_SISAT(NU_PROTOCOLO_SISAT);
CREATE INDEX R_244 ON OCORRENCIA_SISAT(NU_OCORRENCIA_ANTERIOR);
CREATE INDEX XIF200OCORRENCIA_SISAT ON OCORRENCIA_SISAT(
    CO_ENTIDADE_EXECUCAO, CO_SETOR_EXECUCAO);
CREATE INDEX XIF201OCORRENCIA_SISAT ON OCORRENCIA_SISAT(
    CO_ENTIDADE_EXECUCAO, NU_CONTRATO, NU_PRETENDENTE);
CREATE INDEX OCORRENCIA_SISATX12 ON OCORRENCIA_SISAT(IN_PRIORIDADE_TAREFA,DT_PREVISAO_FIM);
CREATE INDEX OCORRENCIA_SISATX13 ON OCORRENCIA_SISAT(NU_PRETENDENTE);
CREATE INDEX OCORRENCIASISATX01 ON OCORRENCIA_SISAT(CO_IDPAIDOCUMENTOS);
CREATE INDEX R_DOC_GERADO_OCORRENCIA_SISAT ON OCORRENCIA_SISAT(NU_ID_DOCUMENTO_GERADO);


-- =============================================
-- Tabela: LOG_EVENTOS
-- =============================================
CREATE INDEX XIFLOG_EVENTOS_APLIC ON LOG_EVENTOS(CO_APLIC);
CREATE INDEX XIFLOG_EVENTOS_DETALHE ON LOG_EVENTOS(CO_APLIC,CO_DETALHE,DT_DATA_DETALHE);
CREATE INDEX XIFLOG_EVENTOS_IXD ON LOG_EVENTOS(CO_APLIC,DT_DATA_HORA);
CREATE INDEX XIFLOG_EVENTOS_IXDDB ON LOG_EVENTOS(NU_CONTRATO,DT_DATA_HORA);
CREATE INDEX XIFLOG_EVENTOS_PRETDATA ON LOG_EVENTOS(NU_PRETENDENTE,DT_DATA_HORA);
CREATE INDEX XIFLOG_EVENTOS_TABDATA ON LOG_EVENTOS(NO_TABELA,DT_DATA_HORA);
CREATE INDEX XIFLOG_EVENTOS_BASEDATA ON LOG_EVENTOS(NO_BASE,DT_DATA_HORA);
CREATE INDEX XIFLOG_EVENTOS_DATAHORA on log_eventos (dt_data_hora DESC);
CREATE INDEX XIFLOG_EVENTOS_USUARIO ON LOG_EVENTOS(NO_USUARIO, CO_APLIC, DT_DATA_HORA);
CREATE INDEX XIF_LOG_EVENTOS_CONTRATO ON LOG_EVENTOS(NU_CONTRATO);
CREATE SEQUENCE SQ_GEN_LOG_EVENTOS;


-- =============================================
-- Tabela: OPERACAO_CREDITO
-- =============================================
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT XPKOPERACAO PRIMARY KEY (NU_OPERACAO);
CREATE INDEX XIF343OPERACAO ON OPERACAO_CREDITO(
       NU_PRETENDENTE);
CREATE INDEX XIF344OPERACAO ON OPERACAO_CREDITO(
       COD_ENT_SUPERVISOR);
CREATE INDEX XIF346OPERACAO ON OPERACAO_CREDITO(
       COD_ENT_CORRETAGEM,
       CO_UNIDADE_CORRETAGEM);
CREATE INDEX XIF347OPERACAO ON OPERACAO_CREDITO(
       CO_CORRETOR);
CREATE INDEX XIF348OPERACAO ON OPERACAO_CREDITO(
       CO_TIPO_OPERACAO);
CREATE INDEX XIF349OPERACAO ON OPERACAO_CREDITO(
       NU_CPF,
       NU_FASE_ATUAL);
CREATE INDEX XIF350OPERACAO ON OPERACAO_CREDITO(
       NU_OPERACAO_PRINCIPAL,
       NU_OPERACAO);
CREATE INDEX XIF351OPERACAO ON OPERACAO_CREDITO(
       CO_ENTIDADE_CADASTRAMENTO);
CREATE INDEX R_USUA_CANCELAMENTO__OPERACAO ON OPERACAO_CREDITO(CO_USUARIO_CANCELAMENTO);
CREATE INDEX R_CESSIO_OPERACAO_CREDITO ON OPERACAO_CREDITO(CO_CESSIONARIO_CREDITO);
CREATE INDEX R_USU_PARECER_JUR__OPERACAO ON OPERACAO_CREDITO(CO_USUARIO_PARECER_JURIDICO);
CREATE INDEX R_USU_PARECER_TEC__OPERACAO ON OPERACAO_CREDITO(CO_USUARIO_PARECER_TECNICO);
CREATE INDEX R_USU_REGISTRO__OPERACAO ON OPERACAO_CREDITO(CO_USUARIO_REGISTRO);


-- =============================================
-- Tabela: DOCUMENTO_OPERACAO
-- =============================================
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT XPKDOCUMENTO_OPERACAO PRIMARY KEY (NU_OPERACAO,
              NU_DOCUMENTO);
CREATE INDEX XIF374DOCUMENTO_OPERACAO ON DOCUMENTO_OPERACAO(
       NU_OPERACAO);
CREATE INDEX XIF376DOCUMENTO_OPERACAO ON DOCUMENTO_OPERACAO(
       NU_GRUPO_DOCUMENTO,
       NU_DOCUMENTO_GRUPO_DOC);
CREATE INDEX XIF377DOCUMENTO_OPERACAO ON DOCUMENTO_OPERACAO(
       CO_USUARIO_RECEBIMENTO);
CREATE INDEX XIF378DOCUMENTO_OPERACAO ON DOCUMENTO_OPERACAO(
       CO_USUARIO_PARECER);
CREATE INDEX XIF379DOCUMENTO_OPERACAO ON DOCUMENTO_OPERACAO(
       NU_PRETENDENTE,
       NU_PESSOA);
CREATE INDEX XIF380DOCUMENTO_OPERACAO ON DOCUMENTO_OPERACAO(
       ID);
CREATE INDEX XIF381DOCUMENTO_OPERACAO ON DOCUMENTO_OPERACAO(
       NU_GRUPO_DOCUMENTO);
CREATE INDEX DOCUMENTO_OPERACAOX01 ON DOCUMENTO_OPERACAO(
       ID_EXTERNO);
CREATE INDEX R_GRUPO_DOC__DOC_OPERACAO ON DOCUMENTO_OPERACAO(NU_GRUPO_DOCUMENTO);
CREATE INDEX R_SISTARQ__DOC_OPERACAO ON DOCUMENTO_OPERACAO(ID);
CREATE INDEX R_PESSOA_PRET__DOC_OPERACAO ON DOCUMENTO_OPERACAO(NU_PESSOA, NU_PRETENDENTE);
CREATE INDEX R_USUARIO_PAREC__DOC_OPERACAO ON DOCUMENTO_OPERACAO(CO_USUARIO_PARECER);
CREATE INDEX R_USUARIO_RECEB__DOC_OPERACAO ON DOCUMENTO_OPERACAO(CO_USUARIO_RECEBIMENTO);
CREATE INDEX R_OPERACAO__DOC_OPERACAO ON DOCUMENTO_OPERACAO(NU_OPERACAO);
CREATE INDEX R_DOC_GRUPO__DOC_OPERACAO ON DOCUMENTO_OPERACAO(NU_GRUPO_DOCUMENTO, NU_DOCUMENTO_GRUPO_DOC);


-- =============================================
-- Tabela: HISTORICO_OPERACAO
-- =============================================
ALTER TABLE HISTORICO_OPERACAO ADD CONSTRAINT XPKHISTORICO_OPERACAO
       PRIMARY KEY (NU_OPERACAO, NU_FASE_OPERACAO, DT_INICIO_FASE);
CREATE INDEX R_USUARIO_HISTORICO_OPERACAO ON HISTORICO_OPERACAO(CO_USUARIO_FASE);
CREATE INDEX R_FASE__HISTORICO_OPERACAO ON HISTORICO_OPERACAO(NU_FASE_OPERACAO);
CREATE INDEX R_OPERACAO__HISTORICO_OPERACAO ON HISTORICO_OPERACAO(NU_OPERACAO);


-- =============================================
-- Tabela: NMOV
-- =============================================
ALTER TABLE NMOV ADD CONSTRAINT XPK_NMOV PRIMARY KEY(NU_MAC,TIPO,COD,CODSERIE,DIA,SEQ);
CREATE INDEX NMOVX01 ON NMOV(NU_MAC,DIA,CONTA,CODMOV);


-- =============================================
-- Tabela: PARCELASCTB
-- =============================================
ALTER TABLE PARCELASCTB ADD CONSTRAINT XPKPARCELASCTB
       PRIMARY KEY (MAC,CO_TIPO,CO_ID,CO_SERIE);
