-- FKs das 10 tabelas grandes
-- Gerado em 2026-04-08

-- =============================================
-- Tabela: CONTROLEVERSAO
-- =============================================
ALTER TABLE CONTROLEVERSAO ADD CONSTRAINT R_CONTROLEVERSAO_SISTARQ FOREIGN KEY (ID) REFERENCES SISTARQ ON DELETE CASCADE;


-- =============================================
-- Tabela: PESSOA_PRETENDENTE
-- =============================================
ALTER TABLE PESSOA_PRETENDENTE ADD CONSTRAINT R_PESSOA_PRINCIPAL
              FOREIGN KEY (NU_PESSOA_PRINCIPAL, NU_PRETENDENTE)
                             REFERENCES PESSOA_PRETENDENTE
                             ON DELETE CASCADE;


-- =============================================
-- Tabela: OCORRENCIA_SISAT
-- =============================================
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT R_ENTIDADE_OCORRENCIA_SISAT
              FOREIGN KEY (CO_ENTIDADE_EXECUCAO)
                             REFERENCES ENTIDADES;
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT R_244 FOREIGN KEY (NU_OCORRENCIA_ANTERIOR)
       REFERENCES OCORRENCIA_SISAT;
ALTER TABLE OCORRENCIA_SISAT ADD CONSTRAINT R_DOC_GERADO_OCORRENCIA_SISAT
              FOREIGN KEY (NU_ID_DOCUMENTO_GERADO)
                             REFERENCES SISTARQ
                             ON DELETE SET NULL;


-- =============================================
-- Tabela: OPERACAO_CREDITO
-- =============================================
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USUA_CANCELAMENTO__OPERACAO
              FOREIGN KEY (CO_USUARIO_CANCELAMENTO)
                             REFERENCES USUARIO;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_CESSIO_OPERACAO_CREDITO
              FOREIGN KEY (CO_CESSIONARIO_CREDITO)
                             REFERENCES ENTIDADES;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USU_PARECER_JUR__OPERACAO
              FOREIGN KEY (CO_USUARIO_PARECER_JURIDICO)
                             REFERENCES USUARIO;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USU_PARECER_TEC__OPERACAO
              FOREIGN KEY (CO_USUARIO_PARECER_TECNICO)
                             REFERENCES USUARIO;
ALTER TABLE OPERACAO_CREDITO ADD CONSTRAINT R_USU_REGISTRO__OPERACAO
              FOREIGN KEY (CO_USUARIO_REGISTRO)
                             REFERENCES USUARIO;


-- =============================================
-- Tabela: DOCUMENTO_OPERACAO
-- =============================================
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_GRUPO_DOC__DOC_OPERACAO
              FOREIGN KEY (NU_GRUPO_DOCUMENTO)
                             REFERENCES GRUPO_DOCUMENTO;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_SISTARQ__DOC_OPERACAO
              FOREIGN KEY (ID)
                             REFERENCES SISTARQ;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_PESSOA_PRET__DOC_OPERACAO
              FOREIGN KEY (NU_PESSOA, NU_PRETENDENTE)
                             REFERENCES PESSOA_PRETENDENTE
                             ON DELETE CASCADE;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_USUARIO_PAREC__DOC_OPERACAO
              FOREIGN KEY (CO_USUARIO_PARECER)
                             REFERENCES USUARIO;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_USUARIO_RECEB__DOC_OPERACAO
              FOREIGN KEY (CO_USUARIO_RECEBIMENTO)
                             REFERENCES USUARIO;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_OPERACAO__DOC_OPERACAO
              FOREIGN KEY (NU_OPERACAO)
                             REFERENCES OPERACAO_CREDITO
                             ON DELETE CASCADE;
ALTER TABLE DOCUMENTO_OPERACAO ADD CONSTRAINT R_DOC_GRUPO__DOC_OPERACAO
              FOREIGN KEY (NU_GRUPO_DOCUMENTO, NU_DOCUMENTO_GRUPO_DOC)
                             REFERENCES DOCUMENTO_GRUPO_DOCUMENTO;


-- =============================================
-- Tabela: HISTORICO_OPERACAO
-- =============================================
ALTER TABLE HISTORICO_OPERACAO ADD CONSTRAINT R_USUARIO_HISTORICO_OPERACAO
              FOREIGN KEY (CO_USUARIO_FASE)
              REFERENCES USUARIO;
ALTER TABLE HISTORICO_OPERACAO ADD CONSTRAINT R_FASE__HISTORICO_OPERACAO
              Foreign key (NU_FASE_OPERACAO)
              References FASE_OPERACAO (NU_FASE_OPERACAO) ;
ALTER TABLE HISTORICO_OPERACAO ADD CONSTRAINT R_OPERACAO__HISTORICO_OPERACAO
              FOREIGN KEY (NU_OPERACAO)
              REFERENCES OPERACAO_CREDITO
              ON DELETE CASCADE;
